stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:20.04
  only:
    - master
  script:
    - apt-get update
    - apt-get install git openssh-client -y
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
    - git remote add deploy "$DEPLOY_SSH_TARGET"
    - GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519" git push deploy HEAD:master
