name: Mirroring

on: [push, delete]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" && git remote add deploy "${{ secrets.DEPLOY_SSH_TARGET }}" && git push deploy master
