name: Mirroring

on: [push, delete]

jobs:
  deploy: 
    steps:
    - uses: actions/checkout@v1
    - uses: net-engine/github-repository-sync-action@v1
      with:
        target_repo_url:
          ssh://dokku@165.227.217.132:tracker
        ssh_private_key:
          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
